### PR TITLE
changed fb:login_button to HTML 5 compatible button

### PR DESCRIPTION
**Pull request by adityapatadia**
Added size paramater and changed login button to HTML 5 compatible button.

### CODE REVIEW

**Comment by lsmith77** [comment]
shouldn't there be a default for this new variable?

**Comment by adityapatadia** [comment]
Yes there should be default value of "small". I am going to commit soon.

On Fri, Mar 9, 2012 at 10:04 PM, Lukas Kahwe Smith <
reply@reply.github.com

**Comment by leek** [comment]
`medium` is the **correct** default value. Please update this PR.

Source: http://www.fbrell.com/xfbml/fb:login-button

**Comment by adityapatadia** [comment]
Again changed the login button. Now it is HTML 5 compatible. Please pull.

**Comment by adityapatadia** [comment]
Can anyone please pull this request and close this issue?

**Comment by diegoholiveira** [comment]
I'll merge it soon as possible.

**Comment by dupuchba** [comment]
Any news about merging this one? @diegoholiveira

**Comment by lsmith77** [comment]
it needs a rebase

**Comment by diegoholiveira** [comment]
I'll do this rebase and do other things to tag 1.2 version on the weekend.

Diego Oliveira
contato@diegoholiveira.com

---- On Thu, 06 Jun 2013 14:26:59 -0300 Lukas Kahwe Smith &lt;notifications@github.com&gt; wrote ---- 

it needs a rebase

**Comment by dupuchba** [comment]
ok @adityapatadia Thx

**Comment by adityapatadia** [comment]
Finally this is going to happen. Please also fix some other bugs and if possible improve docs... ATB :-)

**Comment by diegoholiveira** [comment]
@adityapatadia can you send a PR about what need to be improved on the docs or about the bugs that you found? :)

**Comment by adityapatadia** [comment]
Will send you soon..

**Comment by adityapatadia** [comment]
I think the priority should be #265

**Comment by diegoholiveira** [comment]
Can you provide some documentation about it?

**Comment by diegoholiveira** [comment]
I'm having problems to merge this PR since it look like this code doesn't exist on the author's repo.

I try to do it using the patch available (111.patch), but i got this error:

```
➜  FOSFacebookBundle git:(adityapatadia-master) git apply --check ~/111.patch
error: patch failed: Resources/views/loginButton.html.twig:1
error: Resources/views/loginButton.html.twig: patch does not apply
error: patch failed: Resources/views/loginButton.html.twig:1
error: Resources/views/loginButton.html.twig: patch does not apply
error: patch failed: Templating/Helper/FacebookHelper.php:73
error: Templating/Helper/FacebookHelper.php: patch does not apply
error: patch failed: Templating/Helper/FacebookHelper.php:73
error: Templating/Helper/FacebookHelper.php: patch does not apply
error: patch failed: Templating/Helper/FacebookHelper.php:75
error: Templating/Helper/FacebookHelper.php: patch does not apply
error: patch failed: Resources/views/loginButton.html.twig:1
error: Resources/views/loginButton.html.twig: patch does not apply
```

How to proceed?

**Comment by adityapatadia** [comment]
Hey, @diegoholiveira I think it is my mistake that I deleted the repo before. I will soon send you a new pull request.

**Comment by adityapatadia** [comment]
Please pull this request #268

**Pull request closed without merging**
