### PR TITLE
Commands

### PR DESCRIPTION
**Pull request by marphi**
once again
Commands for support create, list, delete test users.

TestUsers*Command uses the GraphCommand to retrieve the application access token.
In my opinion this function should be provided in fos_facebook.api service.

Commands require the corrected messages.

### CODE REVIEW

**Comment by lsmith77** [comment]
damn sorry .. this pull kinda dropped off my radar. i will do my best to find time to review it this weekend.

**Comment by marphi** [comment]
I fixed bug in my Command class and i changed  bootstrap file to use ClassLoader component.

**Comment by lsmith77** [comment]
great. will check it out over the weekend.

**Comment by lsmith77** [comment]
thx! merged. again soooooorry for the delay. times are a bit crazy with a work project and Symfony2 itself looking for a launch soon.

**Pull request merged**
