### PR TITLE
Facebook log out fix

### PR DESCRIPTION
**Pull request by behcetenuygun**

### CODE REVIEW

**Comment by lsmith77** [comment]
since this changes code you wrote @kriswallsmith, can you review and merge?

**Comment by leek** [comment]
Ping @lsmith77 

Can we get this merged? It is [valid](https://github.com/facebook/php-sdk/blob/master/src/base_facebook.php#L1160).

**Comment by maoueh** [comment]
Is this change gonna logout user from Facebook's website also?

**Comment by behcetenuygun** [comment]
No, only from the session.

**Comment by michelsalib** [comment]
:+1:

**Comment by lsmith77** [comment]
ok .. merging based on the fact that several users seem to have tested this patch.

**Comment by lsmith77** [comment]
manually closing this PR as github seems to be having issues.
a few notes on the PR:
- do not create new features inside the master branch of your fork, create a feature branch
- make sure to actually describe your changes in the commit messages: "Update master" does not describe what you actually changed in those last to commits

**Comment by michelsalib** [comment]
While the commit history is crappy, the merge indeed worked ;)

Thanks @lsmith77 !

**Comment by brentc** [comment]
This does not appear to have been applied to the 2.0 branch. I'm seeing some odd facebook logout issues with that branch, but can't track down the root of the problem. 

What prompted this change on the master branch?  Should this also be applied to the 2.0 branch?

**Comment by maoueh** [comment]
Can you elaborate more on `odd facebook logout issues`?

**Comment by brentc** [comment]
After logging out using the standard Symfony logout process,  when I load the login page the Fb button says "Log Out" rather than "Facebook".

Clicking the Fb button logs me out of Facebook entirely. At which point I can reload the login page and login via facebook (providing my full facebook credentials again).

**Comment by maoueh** [comment]
Here my understanding:
1. You loggout of your `Symfony2` backed site by using your logout action
2. Logout listener of `FOSFacebookBundle` is called and call the code in this new PR which destroy the session.
3. You go to another page and the Fb button still show `Log out`. Why? I think its because you may still have the `fb` cookie around. Can you check this?
4. You click the button, however, destroying the session logs you out of facebook directly. This is what I feared in the first place because it is not same as the old behavior.
5. Clicking the button will reload the page since you are already out of Facebook.
6. At this point, it is like you were not login on your site and not on Facebook anymore, you can login again.

Destroying the session seems to log out completely from Facebook. I would need to test it a bit to check that this is indeed true, but I'm confident it may be the cause of your problem.

**Comment by brentc** [comment]
Close. In Step 2, I'm using the 2.0 branch, so the code in this new PR is not included. I'm wondering if it _should_ be included in the 2.0 branch.

**Comment by maoueh** [comment]
Indeed, I misread you first comment :). Anyhow, check if you still have a cookie after login out of you application. I had a similar problem and I had to remove facebook cookies to make it go away.

**Comment by garak** [comment]
I can confirm this bug for 2.0

**Comment by brentc** [comment]
I have tested the changes in this PR in the 2.0 branch, and these changes _do not_ fix the issue I've described above. Sorry for the distraction. I'll keep trying to track down the problem and open a new issue if the problem is on FOS side.

**Pull request closed without merging**
