### PR TITLE
Markdown formatting of installation paragraph

### PR DESCRIPTION
**Pull request by qpleple**
Added syntax highlighting for code and correct indentation.

### CODE REVIEW

**Comment by lsmith77** [comment]
needs a rebase

**Comment by diegoholiveira** [comment]
I'll close it since the documentation changes a lot since the PR.

**Comment by willdurand** [comment]
it would be nice to have an up to date documentation, with more content...

**Comment by diegoholiveira** [comment]
@willdurand I work a little on it, check it and send me suggestions :)

**Pull request closed without merging**
