### PR TITLE
Remove command to manage the test users, test graph api, access token

### PR DESCRIPTION
**Pull request by marphi**
Hi, 

Facebook has created a tools for getting application access token, manage test users, and Graph API Explorer.
This commands are no longer needed. Proposes to remove them.

### CODE REVIEW

**Comment by lsmith77** [comment]
since you originally submitted the code i guess you should know best .. i guess one advantage of the commands is that it would be easier to script setting up users for functional testing .. no?

**Comment by stof** [comment]
@marphi Could it be possible to make the commands use the tool provided by Facebook instead of removing them ? this would allow people to use it from their Sf2 CLI.

**Comment by marphi** [comment]
I used them, but when FB provide their own tools I switched to them.
If you think that these commands are useful, then close pull.

@stof Facebook provided nice web tools on developers.facebook.com

Sorry for the confusion

**Comment by schmittjoh** [comment]
Ok, I've merged this.

@lsmith, in tests, you can call the Facebook API directly to create test data/users. The commands were just necessary because Facebook had no tools with a GUI, but only the API.

**Pull request merged**
