### PR TITLE
Creating an option to avoid be redirected to facebook login

### PR DESCRIPTION
**Pull request by diegoholiveira**
This will avoid the user be redirect to facebook if he is not logged into facebook. This can give the developer the option to implement another page specific for login (for example, to explain why the project use facebook login).

### CODE REVIEW

**Comment by diegoholiveira** [comment]
@lsmith77 who can take a look on this?

**Comment by lsmith77** [comment]
good question .. i am not aware of any of the FOS guys currently using this Bundle and as the facebook api is generally a life sucking cluster fuck its not the kind of thing any of us do for fun :-/

**Comment by diegoholiveira** [comment]
@stof can you take a look on this and merge or not into the repository? thanks a lot.

**Comment by CeilingHoles** [comment]
I agree that this would be a useful option.

**Pull request closed without merging**
