### PR TITLE
Add facebook logout handler

### PR DESCRIPTION
**Pull request by ornicar**
Add facebook logout handler - we need to clear the facebook cookie when the user logs out

### CODE REVIEW

**Comment by schmittjoh** [comment]
I think `setSession` is only available on version 2.x of the Facebook SDK (which we don't support anymore). 

How about doing this instead:

``` yml
logout:
    delete_cookies: [fbs_appid]
```

**Comment by ornicar** [comment]
The readme still says we support 2.x

```
  [FacebookSDK]
      git=git://github.com/facebook/php-sdk.git
      target=/facebook
      version=v2.1.2
```

**Comment by schmittjoh** [comment]
I've fixed this. 

What do you think about the solution I proposed instead of an extra logout handler?

**Comment by ornicar** [comment]
The problem is that the cookie name is not `fbs_appid`. 'appid' is in fact a placeholder so the cookie name will look more like `fbs_124355678abcd`. That's why I proposed using a logout handler

**Comment by ornicar** [comment]
If the third version of facebook API do not let us set the session anymore, I guess we will have to pass the `appid` value to the logout handler.

**Comment by schmittjoh** [comment]
What are we going to do with this PR? It's not working with the current code, does it?

**Comment by lsmith77** [comment]
@ornicar: ping!

**Comment by ornicar** [comment]
It's not working with the new code, and nobody seems to need it.

**Pull request closed without merging**
