### PR TITLE
Added customization to facebook login button.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by diegoholiveira** [comment]
Can you provide some documentation about this resource?

**Comment by aitboudad** [comment]
Hi, I have relied on this page https://developers.facebook.com/docs/reference/plugins/login/

## Attributes

show-faces:       - specifies whether to show faces underneath the Login button.
width:               - the width of the plugin in pixels. Default width: 200px.
max-rows:        - the maximum number of rows of profile pictures to display. Default value: 1.
scope:             - a comma separated list of extended permissions.
registration-url: - registration page url. If the user has not registered for your site, they will be redirected to the URL you specify in the registration-url parameter.
size:                - Different sized buttons: small, medium, large, xlarge (default: medium).

**Comment by diegoholiveira** [comment]
@Aitboudad can you document this feature on the README.md? When you ready, I'll merge it.

**Comment by aitboudad** [comment]
@diegoholiveira  you can merge it now  ;)

**Pull request merged**
