### PR TITLE
updated path to facebook SDK 

### PR DESCRIPTION
**Pull request by hardchor**
to match PHP SDK 3.\* folder structure and default composer directory

### CODE REVIEW

**Comment by SNProject** [comment]
+1

**Comment by stof** [comment]
When using composer, you don't need to specify the path at all as it handles the autoloading through the classmap.

**Comment by hardchor** [comment]
What about Symfony 2.0 projects?

**Comment by stof** [comment]
Sf 2.0 project may put it anywhere. So saying `to match PHP SDK 3.* folder structure and default composer directory` is wrong in this case (btw, there is nothing related to the SDK folder structure in this path as it changes the path to the clone location, which is not controlled by the SDK but by the user or composer)

And you are changing it in the master rbanch, which is incompatible with 2.0 anyway

**Comment by hardchor** [comment]
Yeah I was thinking that. Just changed it because I got an error when trying to embed it following the documentation (maybe remove that bit?). Sod it then.

**Pull request closed without merging**
