### PR TITLE
Command to support test users 

### PR DESCRIPTION
**Pull request by marphi**
added command to support test users - list, create, delete 

additional command for getting application access token and simple requesting by graph.facebook.com

may be useful

### CODE REVIEW

**Comment by lsmith77** [comment]
could you separate the changes into individual pull requests for each of the additions? then again you should probably wait until we pull https://github.com/FriendsOfSymfony/FacebookBundle/pull/1 sometime this weekend.

**Comment by lsmith77** [comment]
pull/1 is closed .. its rather https://github.com/FriendsOfSymfony/FacebookBundle/pull/4
just needs some final testing before being merged.

**Comment by marphi** [comment]
Hi
I will create a branch for this commands. When you will merge https://github.com/FriendsOfSymfony/FacebookBundle/pull/4 I merge this changes to my branches and then will send pull again.
I have started work on new commands for support real time updates managment.

**Comment by lsmith77** [comment]
ok .. the pull has been merged to master.

**Comment by lsmith77** [comment]
oh and real time update support would be awesome!

**Comment by marphi** [comment]
i sent pull request again https://github.com/FriendsOfSymfony/FacebookBundle/pull/5

**Pull request closed without merging**
