### PR TITLE
Add support of "onlogin" for facebook login button

### PR DESCRIPTION
**Pull request by TintinJS**
With "onlogin" you can specify an action to do once the user is logged in.

### CODE REVIEW

**Comment by TintinJS** [comment]
You have forgot to pull my another pull request, this is just the doc ;)

**Comment by diegoholiveira** [comment]
@walane i'm fixing it since we will use html5 to render the login button (see PR #268)

**Comment by TintinJS** [comment]
Okay

**Comment by diegoholiveira** [comment]
@walane where I can find this attribute documented on Facebook's developers site?
I guess this is not valid anymore, I can't find it on html5 or fb markup.

**Comment by TintinJS** [comment]
Hmm strange... I've found something here https://developers.facebook.com/docs/user_registration/flows/

**Comment by diegoholiveira** [comment]
Take a look here: https://developers.facebook.com/docs/reference/plugins/login/
It's not in the attributes list.

**Comment by TintinJS** [comment]
Arf :/ But i use it on http://www.insomnialille.com/ and it works properly

**Comment by TintinJS** [comment]
EDIT : onLogin is for call a javascript function too

**Comment by diegoholiveira** [comment]
Done. Can you make that it rigth?

**Comment by TintinJS** [comment]
Thank you but sorry i didn't understood your last sentence (i'm french who eat frog)

**Comment by diegoholiveira** [comment]
@walane sorry, i wrote it wrong. I just wanna know if you can test and make sure that is rigth :)

Thanks a lot.

**Comment by TintinJS** [comment]
Okay it's working you're welcome ;)

**Pull request merged**
